---
services:
  buildwar:
    build:
      context: ./
      dockerfile: buildwar.Dockerfile
    volumes:
      - swapdir:/boxfuse-sample-java-war-hello/target
    #command: tail -f /dev/null

  tomcat:
    build:
      context: ./
      dockerfile: tomalp.Dockerfile
    depends_on:
      - buildwar
    ports:
      - '8080:8080'
    volumes:
      - swapdir:/opt/tomcat9/webapps/
    #command: tail -f /dev/null

volumes:
  swapdir:
...